---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install AWX dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"
  when: awx_inventory.dockerhub_base.disabled and awx_inventory.dockerhub_version.disabled

- name: Clone AWX into configured directory.
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    update: "{{ awx_keep_updated }}"
    force: true
    accept_hostkey: true

- name: Ensure admin_password exists
  lineinfile:
    destfile: "{{ awx_repo_dir}}/installer/inventory"
    regexp: '^# admin_password='
    state: present
    line: "admin_password={{ awx_admin_password }}"

- include: awx-install-playbook.yml
  when: awx_run_install_playbook
